### ISSUE TITLE
Using the DOMDocument $any value

### ISSUE THREAD

**Issue by connrs** [WsdlToPhp/PackageGenerator#128]
Hi there,

I do apologise if this is the wrong place to put this question - I'll be happy to submit it elsewhere if there's a better channel.

I'm working with a 3rd party Soap service and the web services has a complex schema. Within one of the types is a <body> that allows anything within it:

    <xs:choice>
        <xs:any/>
    </xs:choice>

When using the generator it's successfully created the class with the $any parameter available:

        public function __construct(\DOMDocument $any = null, \StructType\WSRequest $wSRequest = null, \StructType\WSResponse $wSResponse = null)

This is great. However, when I create a DOMDocument object and then set $any, it fails with the following error:

> Object of class DOMDocument could not be converted to string

Is there something that I'm doing wrong here?

Thanks,
connrs

**Comment by connrs** [comment]
Hey,

I managed to have some success by removing the DOMDocument type and simply allowing `public $any` to have a string type. This allowed me to put some arbitrary XML in which is what the provider of the API want. I'm not sure if this me just abusing your tool here so if you have any advice that'd be great.

**Comment by mikaelcom** [comment]
In order to provide validation of the XML string, it could be useful to validate the string as an XML string (such as the int, float, etc.) such as the other validation rules.

What do you think ?

**Comment by mikaelcom** [comment]
@connrs Could you just tell me if you're XML string contained the `<?xml version="1.0" encoding="utf-8"?>` declaration? I presume that it does not but I think I will keep the DOMDocument as parameter type and call the [saveXML](http://php.net/manual/fr/domdocument.savexml.php) method on the parameter in order to save the string as the property value. Its is safe way to get a valid XML as SOAP value.
Thanks in advance for your answer

**Comment by greggreenhaw** [comment]
Why does any default to a DOMDocument and not just support any object that extends \WsdlToPhp\PackageBase\AbstractStructBase; So is there no way to set any to an object and have it serialize properly?

**Comment by mikaelcom** [comment]
Any is not necessarily and probably never a composition from any object declared by the WSDL, if this is what you're implying at your comment. This is why I don't think this a good idea as it could lead to limitations instead of _openness_ for this property.

**Comment by eduarguz** [comment]
Is there a way to load the `any` content, whether format it is `string` or `DOMDocument` into a proper `\WsdlToPhp\PackageBase\AbstractStructBase` Class ?. 
I mean...  I am pretty sure it is returning another Struct Object, I should be able to do that in my side 🧐.

**Comment by mikaelcom** [comment]
> Is there a way to load the `any` content, whether format it is `string` or `DOMDocument` into a proper `\WsdlToPhp\PackageBase\AbstractStructBase` Class ?.
> I mean... I am pretty sure it is returning another Struct Object, I should be able to do that in my side 🧐.

Could you paste some code in order to understand your thoughts? I don't follow :roll_eyes:. Plus, `pretty sure` and `100% sure` is different, I must have proofs to be able to handle it properly, if it can :wink:

**Comment by eduarguz** [comment]
@mikaelcom thank you for your answer.

I am working with a *"SoapServiceA"* that returns, among another data, a field as `any`, which contains raw xml, then, if I do something like this:

```php
dd($result->getPriceQuote()->getAny())
```

 I can see xml:

```xml
<PriceQuoteInfo xmlns="http://www.sabre.com/ns/Ticketing/pqs/1.0">\n
  <Reservation updateToken="eNc:::ArP0YAYubqJUMrUZlYm5Xw=="/>\n
  <Summary>
    ...
    ...
  </Summary>
</PriceQuoteInfo>
...

```

As you said 

> Any is not necessarily and probably never a composition from any object declared by the WSDL

That is totally correct.

It turns out that in my case, the content of this `any` is a known structure that corresponds to another Service *"SoapServiceB"*.

I could generate the classes for the *SoapServiceB* using this package, and have these very useful classes in my project.

What I would like to do is to be able to use them using a constructor or factory method, something that lets me instantiate all the class based structure, from a string/DomDocument, something like this...

```php
PriceQuoteInfo::loadFromString($result->getPriceQuote()->getAny())
```

I am not asking for the package generator to handle this, I would like to know if that is possible to do in my side, that would be very useful

**Comment by mikaelcom** [comment]
If the `PriceQuoteInfo` class is indeed generated from another WSDL, then you have the helper method `__set_state` that accepts any number of [comma-separated key => value pairs](https://www.php.net/manual/en/language.types.array.php#language.types.array.syntax.array-func) as the onyl argument (see [AbstractStructBase::__set_state](https://github.com/WsdlToPhp/PackageBase#abstractstructbase)).

So you have to map `$result->getPriceQuote()->getAny()` to an associative array of comma-separated key => value pairs. This can be done th way you prefer and you must also handle nested objects.

Am I being clear enough?

**Comment by eduarguz** [comment]
@mikaelcom yes, very clear. `__set_state` should work here

This one is the tricky part.
> you must also handle nested objects

Thank you for the help.
