### ISSUE TITLE
Choice type

### ISSUE THREAD

**Issue by Naktibalda** [WsdlToPhp/PackageGenerator#133]
I have a WSDL file having the following Result type:
```xml
<xs:element name="Result">
    <xs:complexType>
        <xs:sequence>
            <xs:choice minOccurs="1" maxOccurs="1">
                <xs:element minOccurs="0" maxOccurs="1" default="false" name="Success">
                    <xs:simpleType>
                        <xs:restriction base="xs:boolean"/>
                    </xs:simpleType>
                </xs:element>
                <xs:element minOccurs="0" maxOccurs="1" name="Errors">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element minOccurs="1" maxOccurs="unbounded" ref="Error"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:choice>
            <xs:element minOccurs="0" maxOccurs="1" name="Warnings">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element minOccurs="1" maxOccurs="unbounded" ref="Warning"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:element>
```

It allows only one of `Success` and `Errors` elements.
If `Success` element is present, SoapServer ignores `Errors`.

I wasted quite a few hours on it, because I relied on autogenerated classes and hadn't looked at WSDL, so I tried to set it as:
```php
$result = Namespace\StructType\Result(false, $errors, $warnings);
```
Setting `Success` to null value has an interesting effect that neither `Success` nor `Errors` is returned.

I figured out that I can get it working by unsetting `Success` property with
```php
unset($response->Result->Success);
```

It would be great if generated code could throw an exception if multiple values are provided for choice element in constructor.
Setters could throw an exception too or unset other fields (even better).

**Comment by mikaelcom** [comment]
In my opinion, it would effectively be the best option to throw an exception within the setter of one of the properties among the `choice`s properties informing that only one property can be set otherwise the request will not be set properly. 

Can you confirm that setting only one property works and does not need to unset any of the other properties for the request to be properly defined?

**Comment by Naktibalda** [comment]
No, it is necessary to unset.
Otherwise the field is initialized to null value and SoapServer picks it up.

contructor signature is:
```php
public function __construct($success = 'false', \Namespace\StructType\Errors $errors = null, \Namespace\StructType\Warnings $warnings = null)
```

When I tried to call `$result = new \Namespace\StructType\Result();
I got this exception: `
Uncaught exception 'InvalidArgumentException' with message 'Invalid value, please provide a bool, "string" given'`
but that's a different issue.

**Comment by mikaelcom** [comment]
Could you create an issue for the boolean parameter which is not well interpreted for the default value? Thx.

Ok, so it would be similar to [this case](https://github.com/WsdlToPhp/PackageGenerator/issues/48), in addition, it would mean to add the test of the other choice's properties in order to throw an exception informing that only one of the choice's properties has to be set otherwise it will fail. Right?
