### ISSUE TITLE
Non-WSDL Mode?

### ISSUE THREAD

**Issue by dwhiting10** [WsdlToPhp/PackageGenerator#152]
Maybe I missed it, but I have read through the docs and issues for the PackageGenerator/PackageBase and I haven't seen any mention of making web service calls using the non-WSDL mode available for PHP's SoapClient (http://php.net/manual/en/soapclient.soapclient.php).  Is this something that can be done with this tool?

Thanks

**Comment by mikaelcom** [comment]
The aim of this project is to generate a PHP SDK that is the image of the WSDL.

The PackageBase project's aim is to provide basic classes inherited by the generated classes in order to provide basic and useful methods for every class including the classes that send the requests in order to handle the response properly.

These two projects are not suited for a non-WSDL mode in my point of view.

**Comment by dwhiting10** [comment]
Ok thanks for confirming that.
