### ISSUE TITLE
How to enable verbose mode?

### ISSUE THREAD

**Issue by 4n70w4** [WsdlToPhp/PackageGenerator#187]
I want see all raw requests and responces.

**Comment by mikaelcom** [comment]
Rerquests and responses are available using the `getLastRequest` and `getLastResponse` on the service instance, please read https://github.com/WsdlToPhp/PackageBase#usage-2 where all methods are listed

**Comment by 4n70w4** [comment]
Ok, this solves the problem. But I would like all requests to be automatically added to the log file.

**Comment by mikaelcom** [comment]
Then you can create our _own_ implementation of the SoapClient using this approach:
 - Create the [SoapClient classes](https://github.com/WsdlToPhp/PackageEws365/tree/develop/SoapClient)
 - Pass the SoapClient class to the generation [options](https://github.com/WsdlToPhp/PackageEws365/blob/develop/generate.sh#L34)
 - Only override the [__toRequest](https://github.com/WsdlToPhp/PackageEws365/blob/develop/SoapClient/SoapClient.php#L23) method in order to log the request and response

**Comment by 4n70w4** [comment]
I do not want to implementat anything, I want everything ready =)

**Comment by mikaelcom** [comment]
It's not provided
