### ISSUE TITLE
Are MTOM File Transfers suported?

### ISSUE THREAD

**Issue by melmorgado** [WsdlToPhp/PackageGenerator#193]
Are MTOM File Transfers suported?
The soap response contains large files using xop include. The Soap Client is not working.

**Comment by mikaelcom** [comment]
You have to handle the response by yourself [overridding the SoapClient __doRequest](https://github.com/WsdlToPhp/PackageEws365/blob/develop/SoapClient/SoapClient.php#L23) (the sample is not the code you have to write but a project from which you can take example of how to use your own SoapClient) method in order to parse the response and split the boundaries from the XML request then return the XML and store the boundaries parts your way

**Comment by melmorgado** [comment]
Is there an example available? I have tried using a code that uses preg_match, but it failed because the file is too large. The error code was PREG_BACKTRACK_LIMIT_ERROR. 

$resultado =preg_match('/<soap[\s\S]*nvelope>/', $response, $xml_response);
echo preg_last_error();

**Comment by mikaelcom** [comment]
I would recommend simplier process using split with the boundary _identifier_ as the separator to end up with parts on which you loop to extract the file(s) and the XML response.

**Comment by mikaelcom** [comment]
Good luck :wink:

**Comment by mikaelcom** [comment]
no news, good news?
