### ISSUE TITLE
TypeError after package generation

### ISSUE THREAD

**Issue by markus-uderhardt** [WsdlToPhp/PackageGenerator#322]
**Describe the bug**

In our project we generate php files out of a local customer wsdl file.
Recently we needed to migrate from WsdlToPhp/PackageBase v2 to v5 and decided to switch to the newest version of WsdlToPhp/PackageGenerator.

After generating the files in the project we get the following error:

`
Compile Error: Declaration of 
WSDL_NAMESPACE\Generate\StructType\MaintenanceAttachmentFolderDocumentProperty::setPropertyValue(?array $propertyValue = null): 
WSDL_NAMESPACE\Generate\StructType\MaintenanceAttachmentFolderDocumentProperty must be compatible with WsdlToPhp\PackageBase\AbstractStructBase::setPropertyValue(string $name, $value): WsdlToPhp\PackageBase\AbstractStructBase
`

The local wsdl files didn't change.

**To Reproduce**

The package generation works fine.
After generating the files with our local customer wsdl file, the error above is thrown.

**Expected behavior**

No type error, because nothing has changed so far in the used local wsdl files.

**Comment by mikaelcom** [comment]
I assume that the `MaintenanceAttachmentFolderDocumentProperty` struct contains a property named `propertyValue`, am I right?

For your information, since [v4](https://github.com/WsdlToPhp/PackageBase/blob/4.x/src/AbstractStructBase.php), AbstractStructBase contains a public method called [setPropertyValue](https://github.com/WsdlToPhp/PackageBase/blob/4.x/src/AbstractStructBase.php#L47) which is conflicting with the auto-generated method for the property `propertyValue`.

I currently do not have a solution unless I rename the default setPropertyValue, which could produce error for users of this method.

Let me know anyway

**Comment by markus-uderhardt** [comment]
Hey @mikaelcom 
yes you are right it contains a property named `propertyValue`.
Thanks for your answer and the hint :)

I will close the issue for now.
