### ISSUE TITLE
Importing xsd into another xsd causing a problem

### ISSUE THREAD

**Issue by udogan** [WsdlToPhp/PackageGenerator#37]
We have two xsd files which have same named complexTypes in them. One of them is defined as abstract, the other one is not. We are using xsd files like as below:

a.xsd
```xml
...
<complexType name="Campaign" abstract="true">
...
```
b.xsd
```xml
...
<import schemaLocation="a.xsd" namespace="http://foo.com/xmlschema/a" />
...
<complexType name="Campaign">
...
<element name="getCampaignsResponse">
    <complexType>
        <sequence>
            <element name="campaigns" type="b:Campaign" minOccurs="0" maxOccurs="unbounded" />
        </sequence>
    </complexType>
</element>
```

When we use PackageGenerator on b.wsdl, it gives an output of a.wsld's Campaign complexType which called StructCampaign.php. How can we solve this issue? Can we give an option which makes PackageGenerator handle this problem.

**Comment by mikaelcom** [comment]
Could it be possible to have the full WSDL and XSD files (anonymized) at contact@wsdltophp.com? Thks

**Comment by udogan** [comment]
I sent it

**Comment by mikaelcom** [comment]
In order to sumup this issue, this is what has been discussed.

A xsd file defines a struct such as :
```xml
<complexType name="Campaign">
    <sequence>
        <element name="id" type="long" minOccurs="1" maxOccurs="1" />
        <element name="partnerId" type="long" minOccurs="1" maxOccurs="1" />
        <element name="partnerName" type="string" minOccurs="1" maxOccurs="1" />
        <element name="startDate" type="dateTime" minOccurs="1" maxOccurs="1" />
        <element name="endDate" type="dateTime" minOccurs="1" maxOccurs="1" />
        <element name="usageLimit" type="int" minOccurs="1" maxOccurs="1" />
        <element name="name" type="string" minOccurs="1" maxOccurs="1" />
    </sequence>
</complexType>
```

The WSDL file contains this:
```xml
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:cam="http://foo.com/xmlschema/admin/campaign" xmlns:jxb="http://java.sun.com/xml/ns/jaxb" attributeFormDefault="qualified" elementFormDefault="qualified" jxb:version="2.1" targetNamespace="http://foo.com/xmlschema/admin/campaign">
    <complexType abstract="true" name="Campaign">
        <sequence>
            <element minOccurs="0" name="id" type="long" />
            <element name="name" type="string" />
            <element name="startDate" type="dateTime" />
            <element name="endDate" type="dateTime" />
            <element minOccurs="0" name="published" type="boolean" />
        </sequence>
    </complexType>
</schema>
```

But the WSDL does not include at any time the first xsd file. And as you can see the Campaign struct is defined both in the xsd and the WSDL with the same name but a different body.

As the PackageGenerator project and thus the SoapClient does not have knowledge of the first xsd file, it only has knowledge of the Campaign struct defined in the WSDL which is defined as abstract. So it can only generates an abstract class and it won't generate a Campaign struct based on the struct defined in the xsd as the xsd file is never imported/included/loaded/whatever you think.

In my point of view, there is no issue from the PackageGenerator and if the Campaign struct is defined as abstract and also used as a request parameter, it seems to me that it's the issue (which comes from the WSDL). In addition, it seems to me that having two structs with the same name with a different body with one abstract and the other that extends the abstract one is pretty weird, the second one should be named as its purpose in the request in which it is used.

Correct me if I'm wrong with strong details, files and specifications if possible.
