### ISSUE TITLE
Support for Cyrillic alphabet

### ISSUE THREAD

**Issue by mikaelcom** [WsdlToPhp/PackageGenerator#50]
When having this type of element in the WSDL:
```xml
<xs:element name="КонтактнаяИнформация" type="tns:КонтактнаяИнформация" />
```

It is converted to ________________________________________, not so good ....

It would be good to be able to generate the class with the attributes keeping the original name (as Cyrillic seems to be usable in PHP code)

Pardon me if I'm wrong, but it seems to be that @GroxExMachine you're from Russia, could you give some help on this matter?

Thx

**Comment by mikaelcom** [comment]
This method is responsible for this [Generator\Utils:cleanString](https://github.com/WsdlToPhp/PackageGenerator/blob/develop/src/Generator/Utils.php#L207):
```php
/**
 * Clean a string to make it valid as PHP variable
 * @param string $string the string to clean
 * @param bool $keepMultipleUnderscores optional, allows to keep the multiple consecutive underscores
 * @return string
 */
public static function cleanString($string, $keepMultipleUnderscores = true)
{
    $cleanedString = preg_replace('/[^a-zA-Z0-9_]/', '_', $string);
    if (!$keepMultipleUnderscores) {
        $cleanedString = preg_replace('/[_]+/', '_', $cleanedString);
    }
    return $cleanedString;
}
```

**Comment by GroxExMachine** [comment]
Yes, I am from Russia.

I checked, Cyrillic is usable (PHP 5.6). It is looks weird, but I assume, that is just not habitually for me. 
We will have mix in names such as _setКонтактнаяИнформация()_ but it is also works. Will be a harder to write because of need to switch keyboard layout, but autocomplete will handle most of it.

So, I assume, that filter can be adjusted to filter only non visible chars from 0 to 31.

As I remember, some time ago, that was not possible to use Cyrillic in PHP. I did not found information about it now. So, it may depend on PHP version.

**Comment by GroxExMachine** [comment]
Cyrillic also works in PHP 5.2.

**Comment by mikaelcom** [comment]
Thanks for these informations. PHP 5.2 is enough as the generator requires at least PHP 5.3.3.
I think I've found what would be the most useful information at [PHP variable basics](http://php.net/manual/en/language.variables.basics.php) page which provides the regular expression `[a-zA-Z_\x7f-\xff][a-zA-Z0-9_\x7f-\xff]*` in order to ensure a string is usable as a variable. So I think I have to add some unit tests and do some basic tests by generating package from this russian WSDL and I'll see if it works well.

**Comment by mikaelcom** [comment]
I am really surprised, I'm just learning that I could, but never do, use a `é` in a variable/function/class/parameter name :astonished:
