### ISSUE TITLE
WSDL and target servers on different URLs

### ISSUE THREAD

**Issue by mmuruev** [WsdlToPhp/PackageGenerator#58]
Is this feature supported?
Some services provided their test env on different source url but wsdl still remain on main server. I can see only option for PROXY.

**Comment by GroxExMachine** [comment]
Yes, you can change URL at any time when you creating a new service.
```php
$options = array(
    \WsdlToPhp\PackageBase\AbstractSoapClientBase::WSDL_URL => 'https://url/?wsdl',
    \WsdlToPhp\PackageBase\AbstractSoapClientBase::WSDL_CLASSMAP => \ClassMap::get(),
);
```

**Comment by mikaelcom** [comment]
I have no better response unless  you have more details,

thanks @GroxExMachine

**Comment by mikaelcom** [comment]
@mmuruev is it ok for you now?

**Comment by mmuruev** [comment]
Actually not. I mean the case then actually server with data is different when server with wsdl.

**Comment by mikaelcom** [comment]
Then where is the issue?
If the WSDL is the same, the date should be same, right?
If the WSDL is different meaning with different data, then you need to generated a new package, it's normal.

If it's still not clear, could you provide full example, wsdl and data, if possible publicly otherwise via contact@wsdltophp.com, thx.

**Comment by mikaelcom** [comment]
no news is good news 😄
