### ISSUE TITLE
Removing properties from the generated XML

### ISSUE THREAD

**Issue by fbxcelsior** [WsdlToPhp/PackageGenerator#59]
Hi,

I am trying to remove from the generated SOAP request XML properties that can be null. I followed the process described (nillable=true + minOccurs=0) and the properties in the class are correctly generated and unset if set to null... but the XML sent in the SOAP request still has the property field.

Is there any other step I need to do in order for the properties not to appear in the generated XML?

Thank you!

Best regards,

Filipe

**Comment by fbxcelsior** [comment]
Nevermind, got it working! Thanks anyway!

**Comment by mikaelcom** [comment]
Hi,

Indeed, if the property is defined as nillable=true + minOccurs=0, it should be removed from the object then not sent by the SoapClient. If it is still sent (with nill="true" for example), then I would have answered that the best way is to use your own SoapClient class and override the __doRequest method in order to alter the XML before it is actually sent. Overriding the SoapClient can be done such as in this sample in the [PackageEws368 package](https://github.com/WsdlToPhp/PackageEws365/tree/develop/SoapClient).

If you could just give an example of how you proceed, it could be useful to anyone that faces this same type of issue,

thx,

**Comment by fbxcelsior** [comment]
Hi,


I ended up doing like you suggested. Created my own SoapClient class and added the override to the __doRequest method where I searched for elements with xsi:nil="true" and then removed them.

 ```
public function __doRequest($request, $location, $action, $version, $one_way = 0)
{
        $domDocument = new DOMDocument('1.0', 'UTF-8');

        $domDocument->loadXML($request);

        $xPath = new \DOMXpath($domDocument);

        while (($nodeList = $xPath->query('//*[@xsi:nil="true"]')) && $nodeList->length)
        {
            foreach ($nodeList as $node)
            {
                $node->parentNode->removeChild($node);
            }
        }

        return parent::__doRequest($domDocument->saveXML(), $location, $action, $version, $one_way);
}
```

Best,

Filipe
