### ISSUE TITLE
Soap Implementation

### ISSUE THREAD

**Issue by vlahanas** [WsdlToPhp/PackageGenerator#66]
Hello, 

thank you very much for this work, it is indeed a life saver. I have a question, that does not relate to php code generation, rather than the implementation of the core interfaces (AbstractSoapClientBase etc.).

Are these interfaces production ready in terms of performance? I have very little knowledge regarding SOAP, but prior to this, i was using a manually created SoapClient interface and had noticed that some parameters (caching etc.) played an important role in the performance of the client. 

Thanks once again for your work!

**Comment by mikaelcom** [comment]
Hi,

The [PackageBase](https://github.com/WsdlToPhp/PackageBase) project is provided in order to be mainly used by the generated package using this PackageGenerator project.

Nonetheless, if contains useful methods to ease the usage of the native PHP SoapClient class (it does not uses manually created SoapClient classes) as it uses a SoapClient singleton (decorative pattern) which should improve performance. In addition, using the singleton among several consecutive requests allows the cookies to be sent automatically without having to define them manually. It's one advantage among others.

I don't know if you need any additional/specific information but I'll be glad to answser any question.

**Comment by vlahanas** [comment]
Thanks, 

i have to deep a little bit deeper into the code before asking any "real" question, however from what i have seen so far it seems to be a well-designed implementation.
