### ISSUE TITLE
Attributes with xmlns prefix?

### ISSUE THREAD

**Issue by kowach** [WsdlToPhp/PackageGenerator#88]
How can I get namespace prefix for attributes?

WSDL (see mnf):

	<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
	xmlns:mnf="http://localhost/xmlns/MyNsFramework" 
	targetNamespace="http://localhost/xmlns/MyNsFramework" 
	elementFormDefault="qualified" 
	attributeFormDefault="qualified">

	...
	 
	<xsd:element name="GetServiceRequest">
		<xsd:complexType>
			<xsd:complexContent>
				<xsd:extension base="ns1:GetServiceRequestType">
					<xsd:attribute ref="mnf:clientID" use="required"/>
					...
				</xsd:extension>
			</xsd:complexContent>
		</xsd:complexType>
	</xsd:element>
	
PHP generated class:
	
	class GetServiceRequest extends GetServiceRequestType
	{
		/**
		 * The clientID
		 * Meta informations extracted from the WSDL
		 * - ref: mnf:clientID
		 * - use: required
		 * @var string
		 */
		public $clientID;
		...
	}
	
Genrated SOAP request:

	<env:Envelope xmlns:ns1="http://localhost/xmlns/MyService" 
				xmlns:env="http://www.w3.org/2003/05/soap-envelope">
		<env:Body>
			<ns1:GetServicesRequest clientID="myClient">
			...

SOAP should look like:

	<env:Envelope xmlns:ns1="http://localhost/xmlns/MyService" 
				xmlns:env="http://www.w3.org/2003/05/soap-envelope"
				xmlns:mnf="http://localhost/xmlns/MyNsFramework">
		<env:Body>
			<ns1:GetServicesRequest mnf:clientID="myClient">
			...
			
Problem is there is no xmlns:mnf and **clientID**, which should be **mnf:clientID**

**Comment by mikaelcom** [comment]
The XML request is generated by the native PHP SoapClient class so if it does not associate it to the namespace, this means that either it's not necessary or it does not take care of it.

Just to be sure, are you 100% sure that the missing namespace is the origin of the error? If I may, what is the error returned by the Web Service?

However, you can alter the XML request at your will. To do so, you have to override the SoapClient class using your own SoapClient class extending the native SoapClient class in order to add this namespace specifically for this attribute at least. You can start by reading this FAQ section entitled [Can I use my own SoapClient class when sending requests with the generated package?](https://github.com/WsdlToPhp/PackageGenerator/wiki/FAQ#can-i-use-my-own-soapclient-class-when-sending-requests-with-the-generated-package). If you want to have a concrete sample of how to do it, take a look at the [PackageEws65](https://github.com/WsdlToPhp/PackageEws365) project:
- take a look to the [generate.sh](https://github.com/WsdlToPhp/PackageEws365/blob/develop/generate.sh) file in order to have the proper generated composer.json file, line [21](https://github.com/WsdlToPhp/PackageEws365/blob/develop/generate.sh#L21) and [24](https://github.com/WsdlToPhp/PackageEws365/blob/develop/generate.sh#L24)
- take a look to the [SoapClient](https://github.com/WsdlToPhp/PackageEws365/blob/develop/SoapClient/SoapClient.php) class that override the [__doRequest](https://github.com/WsdlToPhp/PackageEws365/blob/develop/SoapClient/SoapClient.php#L23-L27) method in order to alter the XML request before it is actually sent
- you have to figure out how to add the namespace using a clean way or not 😉

**Comment by kowach** [comment]
Origin error from server is:
Exception caused by: org.xml.sax.SAXException: validation error: undeclared attribute: "clientID"   ({com.mnf.xml.validation}COMPLEX_E_UNDECLARED_ATTRIBUTE) at /{http://localhost/xmlns/MyNsFramework/MySerivce}GetServiceRequest[1]/GetServices[1]/ns1:GetServicesRequest[1]/@clientID

If I manually change soap request and add missing namespace and ns prefix to attribute, web service returns valid response.

Thx for the quick response. I'm not happy with altering XML on the fly. I need to sleep this night to clear the mind for next step :)

**Comment by mikaelcom** [comment]
I understand. If you find a way to make the SoapClient add this namespace _natively_, I'm very interested. Altering the request is something I usually do in this particular case, when there is no more _hope_ 😉 .

Good luck and share your workaround if you can, thx

**Comment by kowach** [comment]
I didn't found native solution which could be integrated into WsdlToPhp. Closest thing to namespaced attributes is [this example](http://www.fvue.nl/wiki/Php:_Soap:_How_to_add_attribute_to_SoapVar), but you have to manually build your soap request with SoapVars and it didn't worked in my case.

So I decided for you solution, modifying XML in SoapClient class, method __doRequest.

**Comment by mikaelcom** [comment]
> So I decided for you solution, modifying XML in SoapClient class, method __doRequest.

Sure, the issue does not come from the generated class in any case.

Yes this is the only way and this is where I was expecting to know if you were able to alter the XML request cleanly or not :wink:

**Comment by mikaelcom** [comment]
I'm closing this issue, please can you try the release 2.8.0 then reopen this issue if needed, 

thx
