### ISSUE TITLE
Custom templates and a few small issues

### ISSUE THREAD

**Issue by alpharder** [WsdlToPhp/PackageGenerator#97]
First of all, I want to thank @mikaelcom and all contributors for creating such an amazing and powerful library. I couldn't find library that would have same amount of features (simple types, enums, automatic inheritance, etc 😍 ).

This library's parser is the best.

However, I find imperfect some of the parts of the generated code:
* Code duplication among all of the Enum classes. I think some methods should be moved to the superclass;
* Same for the "__set_state" and "__toString" methods of the Struct classes;
* The general concept of the Service classes is weird. Why do we actually need the "getResult" and "setResult" methods? Why do all services share the same SoapClient? I can reset it, but I have to use several different Services at a time and I don't want to reset them.

I understand that this is only my subjective opinion and probably should not be taken into account while developing the library. But I would not struggle with this if I could customize what code is being generated.
I've tried diving into the source code of this library, but the called classes are hardcoded at each other so I couldn't customize anything.

I am excited by this library's parser. I was excited https://github.com/phpro/soap-client 's customization possibilities. The PHP world would become much better if there was a hybrid of these two libraries,

**Comment by mikaelcom** [comment]
Thanks for such a interesting feedback and thanks for bringing to my attention the phpro/soap-client project which I did not know until now. I must admit this project is way more high level than mine, I'll have to try it by myself.

I know that the code generation is not perfect and that it can be tough to go through even if it has been improved since the very first version of the generator, it takes time to reach perfection...

I'm open to improve this project but I don't think it can be "leveled" up to the same level of customization proposed by the phpro/soap-client project. Nevertheless, improvements can be implemented iteratively if these improvements are detailed as precise as possible.

If you have precise improvements in mind that could both avoid you from struggling and be implemented quickly, feel free to fire some issues detailing your thought. I don't say I'll implement all your enquiries without explanation but I'll try to keep an open mind as much as possible.

**Comment by alpharder** [comment]
I think I'll create a few pull requests when I have enough time to dive deep into the library's code, probably in the next two weeks.

**Comment by mikaelcom** [comment]
a new release has been created and provide a way to use the parsed data independently from the file generation, this is certainly a good starting point to start from in order to refactor the file generation (and even in order to add new programming languages to the package generation if you see what I mean 😉 )

**Comment by alpharder** [comment]
Very good news, thank you!
Will try out soon. Hope I'll have a time for PR's.

9 авг. 2017 г. 14:16 пользователь "Mikaël DELSOL" <notifications@github.com>
написал:

**Comment by mikaelcom** [comment]
Hi there,

I would be very glad if you had time to create some pull request(s) but as I updated the [CONTRIBUTING.md](https://github.com/WsdlToPhp/PackageGenerator/blob/develop/CONTRIBUTING.md) file, you should first create an issue in order to contextualize your PR.

As I would really like to make this project still evolve, feel free to first create new issues, as atomic as possible, so maybe I could work on them depending on their content or we could start discussing about the improvements you'd like to see being implemented,

thx

**Comment by mikaelcom** [comment]
Just to update this topic, I just tried the https://github.com/phpro/soap-client project and even if the code is exciting, using it and looking to what it generates kind of suprised me in a wrong way (without talking about the sample config that breaks).

All I can say is that the 3.x release of this actual project is in preparation and will contain real BCs in order to stay up to date to PHP features as it will also take into account your feedback and the new findings I found so far. The only downside is that it will start not before March 2018

Be patient and stay tuned 😃
